[[bond]]
source = "tpknam1qzer3mmw3shwglxar0tqjxud06ykynjgmed5aphvxu2xcnhlnjc4sxx043f"
validator = "tnam1q8azt2cpqmc6tr2gvg5v62e4jr0t9327yupaf595"
amount = "110"

[bond.signatures]
tpknam1qzer3mmw3shwglxar0tqjxud06ykynjgmed5aphvxu2xcnhlnjc4sxx043f = "signam1qzwh97xd3zyxe9kx8rznukehuyypfpqkqslr0wzmwqw5qeayfdy0kuzw5atuwc3vjxc82jjzx87959zwcg3dnqa0tmxcev8ah3l2eggd3uf7wt"
